name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MLM_LICENSE_TOKEN: ${{ secrets.matlab_token }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
          products: MATLAB_Compiler

      - name: Run build
        uses: matlab-actions/run-build@v2
        with:
          tasks: check test standalone

      - name: Upload Executable
        uses: upload-artifact@v4
        with:
          path: derived/build/hello
